In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
df=pd.read_csv("housearea.csv")
df

area  bedroom  windows   price
0  2600        3        4  550000
1  3000        4        3  565000
2  3200        2        5  610000
3  3600        3        6  595000
4  4000        5        7  760000

In [4]:
new_df=df.drop('price',axis='columns')
new_df

area  bedroom  windows
0  2600        3        4
1  3000        4        3
2  3200        2        5
3  3600        3        6
4  4000        5        7

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model=LinearRegression()

In [8]:
model.fit(new_df,df.price)

LinearRegression()

In [9]:
price_predict=model.predict(new_df)
price_predict

array([555748.17518236, 566916.05839411, 573594.89051094, 642901.45985407,
       740839.41605852])

In [14]:
model.predict([[5000,7,9]])

F:\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([885255.47445285])

In [15]:
model.coef_

array([2.90145985e+01, 2.86313869e+04, 2.90693431e+04])

In [16]:
model.intercept_

278138.6861308225

In [17]:
#model.coef_*model.predict_+model.intercept
2.90145985e+01*5000+2.86313869e+04*7+2.90693431e+04*9+278138.6861308225

885255.4748308224