In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [23]:
df=pd.read_csv("housearea.csv")
df

area  bedroom  windows   price
0  2600        3        4  550000
1  3000        4        3  565000
2  3200        2        5  610000
3  3600        3        6  595000
4  4000        5        7  760000

In [24]:
new_df=df.drop('price',axis='columns')
new_df

area  bedroom  windows
0  2600        3        4
1  3000        4        3
2  3200        2        5
3  3600        3        6
4  4000        5        7

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model=LinearRegression()

In [27]:
model.fit(new_df,df.price)

LinearRegression()

In [30]:
pprice_predict=model.predict(new_df)
pprice_predict

array([555748.17518236, 566916.05839411, 573594.89051094, 642901.45985407,
       740839.41605852])

In [31]:
model.predict([[3000,3,7]])

F:\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([654562.04379557])

In [32]:
model.coef_

array([2.90145985e+01, 2.86313869e+04, 2.90693431e+04])

In [33]:
model.intercept_

278138.6861308225

In [ ]:
2.90145985e+01*3000+2.86313869e+04*3+2.90693431e+04*7+