In [273]:
import pandas as pd
import numpy as np
df=pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [274]:
df=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [275]:
x=df.drop(df.Survived,axis='columns')
y=df.Survived

In [276]:
dummy=pd.get_dummies(x.Sex)
dummy.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [277]:
x=pd.concat([x,dummy],axis='columns')
x.head(4)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0

In [278]:
x.drop(['Sex','male'],axis='columns',inplace=True)
x.head(4)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1

In [279]:
x.Age = x.Age.fillna(x.Age.mean())
x.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [280]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [281]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [282]:
model.fit(X_train,y_train)

GaussianNB()

In [283]:
model.score(X_test,y_test)

0.7686567164179104

In [286]:
model.predict(X_test.head(10))

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [287]:
model.predict_proba(X_test.head(10))

array([[0.30912007, 0.69087993],
       [0.97026795, 0.02973205],
       [0.9673071 , 0.0326929 ],
       [0.0285146 , 0.9714854 ],
       [0.97085713, 0.02914287],
       [0.97026863, 0.02973137],
       [0.94412116, 0.05587884],
       [0.43039455, 0.56960545],
       [0.96895076, 0.03104924],
       [0.96954611, 0.03045389]])

In [288]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.792     , 0.784     , 0.776     , 0.78225806, 0.76612903])