In [93]:
import pandas as pd
import numpy as np
df=pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [94]:
df=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [95]:
x=df.drop(['Survived'],axis='columns')
y=df.Survived

In [96]:
dummy=pd.get_dummies(x.Sex)
dummy.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [97]:
x=pd.concat([x,dummy],axis='columns')
x.head(4)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0

In [98]:
x.drop(['Sex','male'],axis='columns',inplace=True)
x.head(4)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1

In [99]:
x.Age = x.Age.fillna(x.Age.mean())
x.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [100]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [101]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [102]:
model.fit(x,y)

GaussianNB()

In [103]:
model.score(x,y)

0.7777777777777778

In [104]:
model.predict(x.head())

array([0, 1, 1, 1, 0], dtype=int64)

In [105]:
model.predict_proba(x.head(10))

array([[0.9623773 , 0.0376227 ],
       [0.02710002, 0.97289998],
       [0.42013551, 0.57986449],
       [0.05191761, 0.94808239],
       [0.96781365, 0.03218635],
       [0.9666005 , 0.0333995 ],
       [0.65571134, 0.34428866],
       [0.9320816 , 0.0679184 ],
       [0.42680247, 0.57319753],
       [0.18812817, 0.81187183]])

In [106]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x, y, cv=5)

array([0.70949721, 0.79775281, 0.78089888, 0.75842697, 0.79213483])